name: "React-app Container Deployment Pipeline"

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Use Docker Hub for Docker registry
  REGISTRY: docker.io
  # Your Docker Hub username
  DOCKER_HUB_USERNAME: aounallah
  # Your Docker Hub password
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  # Docker image name
  IMAGE_NAME: aounallah/react-app

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: Debug Environment Variables
              run: |
                echo "DOCKER_HUB_USERNAME: $DOCKER_HUB_USERNAME"
                echo "DOCKER_HUB_PASSWORD: $DOCKER_HUB_PASSWORD"

    # integration:
    #     uses: ./.github/workflows/integrate.yml
    #     permissions:
    #         contents: read
    # delivery:
    #     needs: [integration]
    #     uses: ./.github/workflows/deliver.yml
    #     permissions:
    #         contents: read
    #         packages: write
    #         id-token: write